# Machine Learning

## HSE, 2024-25

### Home Assignment #1. Numpy Library

The assignment was completed by: Nikita Litvinov

Данное дз – произведение искусства однострочных функций (я постарался =))

### General information

__Publication date:__ 26.01.2025

__Deadline:__ 04:00 05.02.2025

### Grading and penalties

Each task is assessed with 2 points.

The grade for HA is calculated according to the following formula:

$$
s_{\text{numpy}} \times 1/2 ,
$$

where $s_{\text{numpy}}$  — is the number of points you have scored in total on the tasks.


Submitting a task late will incur a penalty of 1 point per day on the final grade for the task, but the delay cannot be more than 3 days.

__WARNING!__ Homework must be completed independently. Assistance from classmates or third parties in solving homework assignments is not permitted. "Similar" solutions are considered plagiarism, and all involved students—including those who copied—will receive no credit for it. The use of generative models (such as ChatGPT and others) in solving homework assignments, beyond using them for reference and educational purposes, to generate assignment code, is considered plagiarism, and such homework will be graded as 0 points.

### Submission format

The format of uploading file will be announced closer to the deadline. You need to upload a file with the extension .ipynb (Python notebook)

### About the assignment

In this homework assignment, you will practice in using numpy library!

In [77]:
import numpy as np

In all problems it is necessary to write the solution code inside the function and check its work by calling the function for the data from the text of the problem.

When solving problems, it is forbidden to use loops (`for`, `while`) and the `if` operator.

Wherever arrays or matrices are encountered, it is implied that it is `numpy.array`.

### 1

Write a function that returns a rounded weighted sum of grades based on given grades and weights. You can calculate the grade for the course :) Let us consider an example, that exam weight is 0.4, homework weight is 0.39 and class weight is 0.21. For example, if the exam is written at 6, homework is 9, and the grade for the attendance is 8, the final grade will be excellent - 8.

In [78]:
def result_mark(weights, marks):
    print(sum(weights*marks))

In [79]:
weights = np.array([0.4, 0.39, 0.21])
marks = np.array([6, 9, 8])
result_mark(weights, marks)

7.59


### 2

Write a function that changes every third (starting from 0) value of an array of integers to a given number. For example, if the input is an array `array([3, 5, 1, 0, -3, 22, 213436])` and the number `-111`, the output should be an array `array([-111, 5, 1, -111, -3, 22, -111])`.

In [166]:
def change_array(array, number): array[::3] = number; print(array) # Единственный способ как смог это записать в одну строку. Считается? - Конечно!

In [167]:
array = np.array([3, 5, 1, 0, -3, 22, 213436])
number = -111
change_array(array, number)

[-111    5    1 -111   -3   22 -111]


### 3

Write a function that gives indices of "close" elements of given arrays, namely those pairs of elements whose modulus of difference does not exceed a given value. For example, if the input is an array `array([1.5, 0.5, 2, -4.1, -3, 6, -1])`, an array `array([1.2, 0.5, 1, -4, 3, 0, -1.2])` and the number `0. 5`, then the output should be an array `array([0, 1, 3, 6])` (_**important: not `tuple`, but a one-dimensional array of type `numpy.ndarray` (i.e. `.ndim` from it equals 1)!**_).

In [44]:
def find_close(array1, array2, precision):
    print(np.where(np.abs(np.abs(array1) - np.abs(array2)) < precision)[0])

In [45]:
array1 = np.array([1.5, 0.5, 2, -4.1, -3, 6, -1])
array2 = np.array([1.2, 0.5, 1, -4, 3, 0, -1.2])
precision = 0.5
find_close(array1, array2, precision)

[0 1 3 4 6]


### Ошибка? 
[0 1 3 4 6] результат, индекса 4 в примере нет "array([0, 1, 3, 6])", хотя разница по модулю |-3|-|3|=0

### 4

Write a function that makes a block matrix of four blocks, where each block is a given matrix. For example, if the input is a matrix
$$
\begin{pmatrix}
0 & 1 & 2\\
3 & 4 & 5\\
\end{pmatrix},
$$
then the answer is the matrix
$$
\begin{pmatrix}
0 & 1 & 2 & 0 & 1 & 2\\
3 & 4 & 5 & 3 & 4 & 5\\
0 & 1 & 2 & 0 & 1 & 2\\
3 & 4 & 5 & 3 & 4 & 5\\
\end{pmatrix}
$$

In [48]:
def block_matrix(block):
    print(np.block([[block, block], [block, block]]))

In [49]:
block = np.array([[0, 1, 2], [3, 4, 5]])
block_matrix(block)

[[0 1 2 0 1 2]
 [3 4 5 3 4 5]
 [0 1 2 0 1 2]
 [3 4 5 3 4 5]]


### 5

Write a function that computes the product of all non-zero diagonal elements on the diagonals of a given square matrix. For example, if the input is a matrix
$$
\begin{pmatrix}
0 & 1 & 2\\
3 & 4 & 5\\
6 & 7 & 8\\
\end{pmatrix},
$$
then the answer is 32.

In [82]:
def diag_prod(matrix):
    print(np.prod(np.diag(matrix)[np.diag(matrix) != 0]))

In [83]:
matrix = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
diag_prod(matrix)

32


### 6

To improve the performance of some machine learning algorithms, it can be useful to use [data normalization](https://vk.cc/8xmfQk) to bring the features in a sample to the same scale - namely, subtract the mean of its values from each column and divide by their standard deviation. Write a function that normalizes the input matrix (column by column). For example, if the input matrix is
$$
\begin{pmatrix}
1 & 4 & 4200\\
0 & 10 & 5000\\
1 & 2 & 1000\\
\end{pmatrix},
$$
then the result with accuracy to hundredths will be the matrix
$$
\begin{pmatrix}
0.71 & -0.39 & 0.46\\
-1.41 & 1.37 & 0.93\\
0.71 & -0.98 & -1.39\\
\end{pmatrix}
$$

_Hint. Keep in mind that you should not get any nan in your matrix. Think in what case they can occur and how to get around this problem._


In [89]:
def normalize(matrix): # Дабы избежать деления на 0 заменяем 0 на 1 у std
    print(np.round((matrix - matrix.mean(axis=0)) / np.where(matrix.std(axis=0) == 0, 1, matrix.std(axis=0)), 2))

In [91]:
matrix = np.array([[1, 4, 4200], [0, 10, 5000], [1, 2, 1000]])
normalize(matrix)

[[ 0.71 -0.39  0.46]
 [-1.41  1.37  0.93]
 [ 0.71 -0.98 -1.39]]


### 7

Write a function that calculates some primal of the given polynomial (take your favorite number as a constant). For example, if the input is an array of coefficients `array([4, 6, 0, 1])` corresponding to the polynomial $4x^3 + 6x^2 + 1$, the output is an array of coefficients `array([1, 2, 0, 1, -2])` corresponding to the polynomial $x^4 + 2x^3 + x - 2$.

In [125]:
def antiderivative(coefs, fav_num):
    print(np.append(coefs / np.arange(coefs.size, 0, -1), fav_num))

In [128]:
coefs = np.array([4, 6, 0, 1])
antiderivative(coefs, 8)

[1. 2. 0. 1. 8.]


### 8

Write a function that makes the given [triangular](https://en.wikipedia.org/wiki/Triangular_matrix) matrix symmetric. For example, if the input is a matrix
$$
\begin{pmatrix}
1 & 2 & 3 & 4\\
0 & 5 & 6 & 7\\
0 & 0 & 8 & 9\\
0 & 0 & 0 & 10\\
\end{pmatrix},
$$
then the output should be the matrix
$$
\begin{pmatrix}
1 & 2 & 3 & 4\\
2 & 5 & 6 & 7\\
3 & 6 & 8 & 9\\
4 & 7 & 9 & 10\\
\end{pmatrix}.
$$

In [140]:
def make_symmetric(matrix):
    print(matrix + matrix.T - np.diag(np.diag(matrix)))

In [141]:
matrix = np.array([[1, 2, 3, 4], [0, 5, 6, 7], [0, 0, 8, 9], [0, 0, 0, 10]])
make_symmetric(matrix)

[[ 1  2  3  4]
 [ 2  5  6  7]
 [ 3  6  8  9]
 [ 4  7  9 10]]


### 9

Write a function that creates a rectangular matrix of m equal rows filled with consecutive natural numbers from a to b inclusive in ascending order. For example, if m = 5, a = 3, b = 10, the output will be the matrix
$$
\begin{pmatrix}
3 & 4 & 5 & 6 & 7 & 8 & 9 & 10\\
3 & 4 & 5 & 6 & 7 & 8 & 9 & 10\\
3 & 4 & 5 & 6 & 7 & 8 & 9 & 10\\
3 & 4 & 5 & 6 & 7 & 8 & 9 & 10\\
3 & 4 & 5 & 6 & 7 & 8 & 9 & 10\\
\end{pmatrix}
$$

In [155]:
def construct_matrix(m, a, b):
    print(np.tile(np.arange(a, b + 1), (m, 1))) # Гугл-гугл ты могуч, ты гоняешь стаи туч – я скоро женюсь на доке numpy...

In [156]:
m = 5
a = 3
b = 10
construct_matrix(m, a, b)

[[ 3  4  5  6  7  8  9 10]
 [ 3  4  5  6  7  8  9 10]
 [ 3  4  5  6  7  8  9 10]
 [ 3  4  5  6  7  8  9 10]
 [ 3  4  5  6  7  8  9 10]]


### 10

Write a function that computes the [cosine proximity](https://en.wikipedia.org/wiki/Cosine_similarity) of two vectors. For example, if the vectors `array([-2, 1, 0, -5, 4, 3, -3])` and `array([0, 2, -2, 10, 6, 0, 0])` are given as input, the answer is -0.25.

In [160]:
def cosine_similarity(vec1, vec2):
    print(np.dot(vec1, vec2) / (np.linalg.norm(vec1) * np.linalg.norm(vec2)))

In [161]:
vec1 = np.array([-2, 1, 0, -5, 4, 3, -3])
vec2 = np.array([0, 2, -2, 10, 6, 0, 0])
cosine_similarity(vec1, vec2)

-0.25
